# Generated by Django 5.0.7 on 2024-07-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='lesson',
        ),
    ]
