# Generated by Django 5.0.4 on 2024-07-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0002_remove_well_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='содержание'),
        ),
    ]
